### ISSUE TITLE
CSS: Lists are different font/style from rest of page.

### ISSUE THREAD

**Issue by gratefulcheddar** [decred/dcrdocs#104]
![screen shot 2017-03-10 at 12 05 26 am](https://cloud.githubusercontent.com/assets/12915233/23784051/4e83dedc-0525-11e7-8e43-c8921a72204e.png)

Also, 3 is within `<p>` tags inside `<li>` tags, while 1 and 2 are simply inside `<li>` tags. These have two different styles (I also don't know why the markdown is being parsed differently with this list).

**Comment by jholdstock** [comment]
@jcvernaleo please assign this issue to me.

@gratefulcheddar - It seems that `<li>` text is being displayed using font-size "1.8rem" whereas the normal paragraph text is displayed using "1.7rem". This is easily fixed in `./tpldcrdocs/css/main.css`.

Can you provide a current example of where items in the same list are drawn with different styles? I cannot find one (I have looked in `master` and on https://docs.decred.com - cannot locate your screenshot).

**Comment by jcvernaleo** [comment]
@jholdstock It appears that github will not let me assign the issue to you.  You are a contributor (I just merged your other PR in).  So I will assign the issue to me just as a placeholder so no one else goes and works on it but it is all yours.  Totally don't understand what github is doing here though.

**Comment by gratefulcheddar** [comment]
@jholdstock that screenshot was from local changes, sorry. 

I think all the text should be the same size/style except for the code snippets and headers...

**Comment by jholdstock** [comment]
Table text is set to 1.8rem also so I will make that consistent with the others.
