### ISSUE TITLE
Verifying Binaries: use longer keys

### ISSUE THREAD

**Issue by xaur** [decred/dcrdocs#1046]
Currently [Verifying Binaries](https://docs.decred.org/advanced/verifying-binaries/) is instructing to use this command:

```
gpg --keyserver pgp.key-server.io --recv-keys 0x518A031D
```

4-byte (8-character) key ids are [insecure](https://security.stackexchange.com/questions/84280/short-openpgp-key-ids-are-insecure-how-to-configure-gnupg-to-use-long-key-ids-i). Instead, I suggest to use the full fingerprint:

```
gpg --keyserver pgp.key-server.io --recv-keys F516ADB7A069852C7C28A02D6D897EDF518A031D
```

Please don't trust the above fingerprint and verify it yourself with `gpg --list-keys --with-subkey-fingerprint "release@decred.org"` - this should print the full fingerprint for the release subkey.

Bonus task 1: I'm not sure why we use _subkey_ to fetch the key. Perhaps someone experienced with gpg can advise. If we should use the key instead, use `FD13B6835E248FAF4BD1838D6DF634AA7608AF04`.

Bonus task 2: As of writing `pgp.key-server.io` did not serve Decred's key to me ("keyserver receive failed: No data"). Other keyservers worked. Maybe this is temporary, but if not, we should use another keyserver.

**Comment by jholdstock** [comment]
Similar/identical instructions also exist on the solo voting page, so they should be updated in both places if we make changes

**Comment by davecgh** [comment]
It's using a subkey because they have different purposes.  One is an _encryption_ key and the other is a _signing_ key.  People verifying signatures should be fetching the _signing_ key.

Using subkeys also enables the possibility to have multiple signing subkeys associated with the primary key so that should it become necessary to revoke/update, it's possible without forcing people to associate with a new identity.

I agree with using the long id of the signing subkey, which is indeed `F516ADB7A069852C7C28A02D6D897EDF518A031D` as the issue states.
