### ISSUE TITLE
Add page explaining redeem script for VSP voting and recovery methods for it

### ISSUE THREAD

**Issue by matheusd** [decred/dcrdocs#1065]
We have a warning in the "Using Decrediton" page and we'll be adding a warning to Decrediton itself but it would probably be better to add a page with a more thorough explanation of the importance of the redeem script for VSP voting, why it's needed, what happens if it's lost and the VSP disappears and potential recovery methods for it.

**Comment by jholdstock** [comment]
- https://www.reddit.com/r/decred/comments/fim5j2/stakepool_failure_caused_me_to_lose_all_my/
- https://matrix.to/#/!dhHYPTtCtvPSUfTepT:decred.org/$158423053938641AbMlW:decred.org?via=decred.org&via=matrix.org&via=zettaport.com


A user has recent run into serious problems because of a lack of clear warnings around redeem scripts, there are various places we can improve:

- https://docs.decred.org/faq/proof-of-stake/voting-service-providers/#6-what-safeguards-are-in-place-to-stop-voting-service-provider-vsp-owners-disappearing-with-the-funds-in-the-tickets-they-vote-for
- https://docs.decred.org/wallets/decrediton/using-decrediton/#backup-redeem-script

**Comment by pLabarta** [comment]
I've collected the info and will begin working to improve several sections:
- PoS>How to Stake>Using a VSP
- Wallets>Decrediton>Using Decrediton>Backup redeem script
- FAQ>VSP>What safeguards...

Should I add a new question to the FAQ specifying how to backup the script or recovery methods?

Regarding recovery methods, I understand that if at least one of the user's ticket purchased through the VSP voted or was revoked, the script can be recovered using dcrdata. This are my notes:

"If one of the tickets the user purchased through that VSP has already voted or has been revoked, the redeem script has been stored on the Decred blockchain. It can be recovered through DCR Data by searching for the transaction and looking into the decoded JSON for the ASM scriptSig. This one should be a long string separated by a white space. The second part of the string is the redeem script used."

Example: https://dcrdata.decred.org/api/tx/decoded/7b673da715c52d68331fe0bdd4ea69f00474eccf14a9285c4d90e89fe9db5d6c?indent=true

![redeemscriptdcrdata](https://user-images.githubusercontent.com/10605905/78907914-b96ea100-7a57-11ea-82c1-eb028353aa3e.png)

Is this correct?

There are also more complex recovery methods for worse case scenarios where none of the tickets voted but results are not guaranteed and require coding skills.

**Comment by jholdstock** [comment]
Done in #1089
