### ISSUE TITLE
drcdocs and the wiki

### ISSUE THREAD

**Issue by kargakis** [decred/dcrdocs#18]
https://docs.decred.org/
https://wiki.decred.org/Main_Page

Why are those two separate and not one thing? What purpose each of them serves? When should I visit the one over the other?

**Comment by jolan** [comment]
Wiki can probably be removed in favor of docs once some more content is moved over.

**Comment by jcvernaleo** [comment]
Those are separate pages since they are different things.  docs is a site for static (and hopefully well reviewed) content while the wiki is a wiki (as in editable much quicker) so more likely to have things that could change faster, are work in progress, or user submitted content.  As is the wiki hasn't been used too heavily and the docs site is where you go for documentation.  There are still things the wiki could be good for though, especially since people can edit it without going through the github PR/review process.

**Comment by kargakis** [comment]
I am not in favor of one over the other, but having a sole place for docs
where everyone contributes will be much more consistent than maintaining
docs in two different places. At some point, one will start lagging behind
and eventually end up outdated.

**Comment by raedah** [comment]
No one can edit the wiki because there is no way to create accounts.

**Comment by fai04d** [comment]
I'm in favor of closing the wiki. See my forum post for more info (https://forum.decred.org/threads/documentation.4998/#post-23934).

I don't think it's good form to expect people to check two document sites, especially when the forum is where most people will go when looking for the latest info. Plus, now that we have the on-going documentation contracts there's incentive to keep everything up to date anyway.

Also, with greater collaboration with the dev team, we can ensure that new changes/features are documented in advance. Put the new docs in a separate branch then when the new version is released we just merge the branch.

**Comment by jcvernaleo** [comment]
At this point, I'm also in favor of getting rid of the wiki and moving totally to docs.decred.org

I do think we have to make sure ALL content from the wiki is also on the docs site first though.  There probably isn't much that is exclusively on the wiki, but someone will still need to check carefully.

**Comment by xaur** [comment]
Quick check suggest its not too hard:

* last change on 2016-03-04
* there are not that many [pages](https://wiki.decred.org/Special:AllPages)
* there are no discussion pages
* no [Files](https://wiki.decred.org/Special:ListFiles)

**Comment by jholdstock** [comment]
+1 in favour of removing the wiki.

As per jcv's (I guess @jcvernaleo?) forum post I will spend some time looking through wiki and open issues for any content I find missing in dcrdocs

**Comment by jcvernaleo** [comment]
@jholdstock someone beat me to my normal 3 letter nick on github (and twitter) by just a short amount of time which is why I have the different names.  I'm still a but annoyed by it :(

**Comment by jholdstock** [comment]
I have just spent checking the wiki and I think everything is now moved over to dcrdocs with three exceptions:

1. Transaction Details (#117)
1. Outdated information/guides which are now redundant due to dcrdocs
1. Three pages which have been translated to Spanish:
-- https://wiki.decred.org/Main_Page/es
-- https://wiki.decred.org/Introduction/es
-- https://wiki.decred.org/Decred_Constitution/es

#95 probably needs to be implemented before the Spanish pages are moved over. I think wiki will then become completely redundant

**Comment by jcvernaleo** [comment]
Agreed, once #95 goes in we can move the spanish pages over and kill the wiki.

**Comment by jcvernaleo** [comment]
#96 is in so the es pages from the wiki can be moved over.
