### ISSUE TITLE
Improve translation guide

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#183]
Some suggestions from @karamble 
- one small thing i miss in your transaltion manual is the part on how someone set up the environment on github. that would be a nice addition and thats actually the hardest part for people new to working with github (open account, fork the docs repository, create a working branch, commit work)
- its worth to mention that we would like to see a commit for every documentfile.md that is finished translation with a fixed pre-title "ru translation filename.md" so it will be nice to track progress in the github commit history and you allways know on which date it was last edited and if there is a newer english original version of it.

**Comment by jholdstock** [comment]
I think these two guides contain pretty much everything needed to contribute to dcrdocs via github:
1. https://help.github.com/articles/fork-a-repo/
2. https://help.github.com/articles/syncing-a-fork/
We can just link to these instead of writing up our own guide.

**Comment by jcvernaleo** [comment]
I do not think that the github/fork setup belongs with this at all.

If anything that info should be in https://github.com/decred/dcrdocs/blob/d4dabd7c53a326363cc884e5053493afe0758715/docs/advanced/contributing.md and we link to that (since a translation is a contribution).

If there is something missing from that we can add it, but I do not want fork info (which would end up duplicated elsewhere) in the translation section of the readme.  Just link to the contribution page.

**Comment by jcvernaleo** [comment]
As for the 2nd point, that is totally fine with me.  If that makes it easier for translators, then we should do it that way.

**Comment by jholdstock** [comment]
Agreed about the fork/PR etc info
