### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrdocs#240]

**Comment by Arriu** [comment]
I've taken on this issue. I'm going to tackle it in two stages. First i'm building a list by going over https://docs.decred.org/ from top to bottom selecting any words I think might be hard to understand to people new to the space. I'm being quite extensive, since i think redundancy can't hurt here. Anyone is free to add to the list if they feel there are words missing. Second I'll be writing actual Glossary itself, making as much use of citable sources as possible.

**Comment by dajohi** [comment]
@arriu can you submit a PR?

**Comment by Arriu** [comment]
I'm sorry I hadn't communicated this here earlier. I haven't found any time to spend on DCR in general in the past half year and I can't forsee when i'll be able to do so again just yet. Please remove me from this issue. I'd alrdy communicated on slack that if anyone else showed up they were absolutely free to take this up. I also shared the incomplete list of terms I'd made there. Unfortunately, I've been away from it all for so long I don't even remember how to use git and github. I hope this hasn't caused anyone inconvenience and I still hope to contribute in the future.

**Comment by jholdstock** [comment]
Closing this - glossary work will be tracked in #589

**Comment by jholdstock** [comment]
Closing this - glossary work will be tracked in #589

**Comment by jholdstock** [comment]
Closing this, will use #589 for glossary work
