### ISSUE TITLE
POS broken link

### ISSUE THREAD

**Issue by pedrotst** [decred/dcrdocs#294]
The main page of the doc https://docs.decred.org/getting-started/obtaining-dcr/#stake-mine-for-decred-proof-of-stake-pos has a broken link to POS

**Comment by gratefulcheddar** [comment]
The PoW link above it is also broken

**Comment by jholdstock** [comment]
This broken link did not cause `mkdocs build --strict` to fail. I think this is because the url did not include the file suffix `.md`.

When ```/mining/overview#1-proof-of-work-mining``` is changed to ```/mining/overview.md#1-proof-of-work-mining``` the build logs the expected error message.

There are three other places in the code where we have links not including `.md`, I have opened #298 to address this.
