### ISSUE TITLE
Create guide for using Decredition

### ISSUE THREAD

**Issue by gratefulcheddar** [decred/dcrdocs#32]
Create guide for using Decredition

**Comment by jcvernaleo** [comment]
Just want to warn/remind you on this one that Decrediton is much younger than any of the other tools so it is in more of a state of flux than any of the others.  So we might either want to make it the last thing to create a guide for, or expect that any guide done might need revising sooner rather than later.

That said, the process of writing a guide for it could provide some useful feedback for any rough points in it.

**Comment by gratefulcheddar** [comment]
Hope to have this done by 1.0.0. Need to add a section in getting-started/install-guide.md and a new decrediton-setup.md and using-decrediton.md in a new "Decrediton" navigation section.
