### ISSUE TITLE
Add youtube channel

### ISSUE THREAD

**Issue by dajohi** [decred/dcrdocs#424]
Add the youtube decred channel.
https://www.youtube.com/channel/UCJ2bYDaPYHpSmJPh_M5dNSg

**Comment by jholdstock** [comment]
I'm hesitant to do this because I'm aware that this style of youtube link can be changed at any moment and it's a pain to keep updating. Do we have any permalinks?

**Comment by jholdstock** [comment]
https://support.google.com/youtube/answer/2657968?hl=en-GB

I'm not a big youtube guy, but skimming this page gives me the impression that we can apply for a custom URL. I think our channel meets all the requirements

**Comment by thatssixzs** [comment]
Yeah, I recently did this for a channel. You simply need to "link channel to website" (standard google webmaster verification process) then you can have the youtube.com/c/custom-name. 

To associate a website simply have a domain member/channel admin goto https://www.youtube.com/advanced_settings

**Comment by realingsoc** [comment]
Just wanted to update everyone on the situation. It appears Google will not allow you to use various custom URLs for a number of undisclosed reasons - that they do not provide support on or comment on.

Unfortunately, "decred" and "decredproject" are not available. I suspect this is due to the fact that the YouTube Google account is not the original account Google associated with "decred" and "decredproject". I've verified the website to this new account, but still no luck.

Unless we can find a resolution to this problem, we'll need to pick a different handle to use for the custom URL (e.g., "https://youtube.com/decred[something]").

**Comment by bebrites** [comment]
dcr?

**Comment by realingsoc** [comment]
https://youtube.com/decredchannel worked. Good to go.
