### ISSUE TITLE
Possible non-javascript theme

### ISSUE THREAD

**Issue by fai04d** [decred/dcrdocs#43]
Some users have suggested they would prefer the docs website to have a non-javascript option. This theme may be useful although I haven't looked closely at it:

https://chocolatey.org/packages/mkdocs-material/1.0.0-beta

**Comment by jcvernaleo** [comment]
I'm one of those people who uses no-script on most sites and then just whitelists things as needed/trusted so I'm not a javascript apologist at all, but I have some doubts as to the ability to get the docs to work without js.  The mathjax stuff, mostly on the research tab, being one of the biggest issues.

If there is a theme for mkdocs that can do it, great.  I haven't looked into that theme closely enough to say for sure, but I would prefer not to use a pre-release theme.

Also, since the docs site can read entirely locally (and therefore fully audited), I'm less worried about the javascript since one can always run it local (or even better local in a networkless vm) if one is feeling particularly security conscious.

**Comment by xaur** [comment]
Aforementioned discussion here: https://forum.decred.org/threads/documentation.4998/

In that thread some points were made in defense of javascript and webfonts:

* self-hosting: javascript and web fonts are okay as long as they come from Decred-controlled domains (no 3rd party resources)
* Subresource Integrity: for 3rd party resources we can pin their hashes in our HTML documents
* MathJax needs javascript to render formulas

Briefly: not requiring javascript and webfonts to read the docs is totally better than any other conceivable setup.

Here's my reasoning.

Self-hosting is a _huge_ step compared to most other sites. Self-hosting resources is certainly better than not. Same for Subresource Integrity -- if it so happens that you have to use 3rd party resources, using all available tools to protect integrity is better than not.

But still the best is to not require javascript at all.

#### Security perspective

The proposed approach is "turn more things on and try to secure them". On the server use self-hosting and Subresource Integrity, on the client update ever-broken browsers and squeeze more security by configuring them. The desire of more features naturally leads to more efforts to secure them.

I'd like to go in the opposite direction -- disable these things entirely and not think about them anymore. I just don't want to activate the whole new attack surface and watch for things like [this svg bug](https://www.wordfence.com/blog/2016/11/emergency-bulletin-firefox-0-day-wild/). W3C and browser vendors are not capable to build deep security, otherwise they would _at least_ ship cookie and javascript whitelisting _out of the box_, like Opera <=12 did. All I see so far is exploding complexity to please ever-hungry web publishers. To feel the problem better and have some fun I recommend [Website Obesity Crisis](http://idlewords.com/talks/website_obesity.htm).

Self-hosting resources also does not imply we have resources to audit them.

#### Accesibility perspective

As worst case example, imagine `man git` would open the browser and fail with "Enable javascript to view this content".

I turn off javascript everywhere I can. Sometimes I read docs in Opera Mini. I hope to start using Lynx someday. It just doen't feel right that I need javascript to _read the docs_.

Ability to run the site locally does not help here. (Although I must admit it is another huge step ahead of most websites).

#### MathJax

Some random ideas:

* Just keep it. It's not used on many pages. Non-JS clients will just not show the formulas.
* Keep it, but make it degrade gracefully. Non-JS clients will show non-rendered formulas in e.g. TeX.
* Render formulas as small images, like Wikipedia (seen it somewhere).
* Put all formulas on a single image.
* "Download this page as PDF" button.
* Move all formulas to a PDF document.

**Comment by jcvernaleo** [comment]
We now host all js locally so this issue is much less.  Other than the forumulas (which aren't in any of the main pages and really have no other good option), this all degrades pretty gracefully without js.  So I think I can safely close this issue.

If someone has other ideas we can look at them when we discuss the themes for this in the near (I hope) future.

**Comment by jholdstock** [comment]
@dajohi  this can be closed thanks to #425
