### ISSUE TITLE
Simplify, Update and improve linguistically

### ISSUE THREAD

**Issue by Arriu** [decred/dcrdocs#503]
The docs are in need of simplification, updating and improvement for consistency and structure.

**Comment by jholdstock** [comment]
Hi @Arriu,

Do you have any specific changes you are planning to implement here? Or do you have any suggested improvements?

I think this issue is a bit too vague to be properly actionable.

**Comment by s-ben** [comment]
Have been thinking of taking a pass just for polish (grammar/flow), but see a decent amount of new text waiting in PRs, as well as suggested changes to jargon and other pages. Don't want to polish content that's disappearing.

**Comment by jholdstock** [comment]
Hey @s-ben, I would say just go for it and make the changes now if you are willing. Obviously don't update pages if you are 100% sure they are getting deleted, but if you were to wait for a time when the entire project is stable then you would probably be waiting forever.

To reduce the amount of potential conflicts, it is advisable to perform changes like this in small chunks. It would be way better to create 10 PRs which update 2 files each, rather than a single PR updating 20 files. Working in small chunks makes mistakes and conflicts less likely, and it also makes reviewing and merging easier.

**Comment by jholdstock** [comment]
Actually I would add to the above, that there isn't anything wrong with making a PR which only makes a single correction or updates a single file. My personal policy is that there isn't really a minimum size for a PR, so long as it makes some meaningful useful change.

**Comment by jholdstock** [comment]
Closing - too vague to be actionable.
