### ISSUE TITLE
Jargon update: change stakepool to Voting Service Provider

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrdocs#581]
As part of the efforts to make Decred more appealing to the general public, we are updating our jargon. 

One of the proposed changes that has rough consensus in the community is changing from stake pool or stakepool to Voting Service Provider (or VSP for short). 

The rationale is explained here:
https://www.reddit.com/r/decred/comments/95r578/proposed_changes_to_decred_jargon/e3uu14p

**Comment by RichardRed0x** [comment]
@linnutee makes a good point about this in the Decrediton issue: https://github.com/decred/decrediton/issues/1615
There are a number of places that would ideally be updated at the same time, to avoid confusion caused by seeing different terms used for the same concept on different platforms.

**Comment by jholdstock** [comment]
This is being voted upon in Politeia, voting is due to end tomorrow (5th of November)

https://proposals.decred.org/proposals/522652954ea7998f3fca95b9c4ca8907820eb785877dcf7fba92307131818c75

If (when) the proposal passes, @RichardRed0x your PR is going to need to be rebased. I can help you with that process if you need some support.

**Comment by s-ben** [comment]
Congrats @RichardRed0x on both Pi proposals! I can help on this as well if there's anything I can do. 

Have made a comment on the sister Issue in Decrediton referencing this Issue, trying to get the ball rolling there. 
https://github.com/decred/decrediton/issues/1615

**Comment by s-ben** [comment]
Nope. Looks like they just slipped through. Open up an Issue?
