### ISSUE TITLE
New font can sometimes load slowly

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrdocs#597]
When I load the docs in an incognito tab, it shows the standard browser font for a while before loading the new font. I assume the same is true for users visiting the docs website for the first time.

Here is a screenshot to show the difference (using a Night Mode add-on)

![image](https://user-images.githubusercontent.com/16287891/44954846-6743c200-aea9-11e8-9d5c-2e6691781e1d.png)

**Comment by jholdstock** [comment]
Good catch @noahpierau. I am not able to reproduce this when I access the site normally over high-speed broadband, but when I simulate a slow 3G connection using the Chrome dev tools I am able to recreate it.

It looks like this issue happens simply because the custom fonts are reasonably large:
- Regular - 287KB
- SemiBold -  285KB
- Code - 102kb

I can investigate if any smaller font files are available which would reduce loading times. I can also look at whether its possible to load the fonts earlier, because at the moment the downloads are only requested after some time - I suspect after all of the .css files have been downloaded.

As a work around, I wil alsol change the default fallback to a san-serif font, which should make the visual impact less jarring.
