### ISSUE TITLE
"go versions N and N-1"

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#621]
The change was made here: https://github.com/decred/dcrdocs/pull/612/files

Any objections if we change it to how it is written in dcrd docs? 

> latest version of Go and the one prior to it

https://github.com/decred/dcrd/pull/1451/files#diff-84c699cc270b08041d0a9b77522f68b8

To me it seems a lot less ambiguous. Thoughts @PrimeDominus @s-ben @RichardRed0x?

**Comment by PrimeDominus** [comment]
Could maybe work I guess. How would you form it into the whole paragraph for use with the example it precedes? Stating it the way it is covers a few bases since Go release compliance wasn't stated on this page at all prior to its current wording. In fact, Go release compliance wasn't even properly stated in the checklist page you've referred to until I had a chat about it with @davecgh and the current wording used is based on the wording I was provided.

**Comment by s-ben** [comment]
i think the `N and N-1` terminology people won't necessarily trip people up, but many won't be familiar with it. have taken a stab at more general, user friendly version:

```For projects using Go, ensure you have either the latest Go release or the one prior installed, as well as a working $GOPATH. All Go code changes for Decred must be compatible with the latest and prior releases of GO.```

**Comment by PrimeDominus** [comment]
@s-ben This reads pretty good. Only thing is `latest and prior releases of Go` at the end may be interpreted as all/many prior releases of Go rather than just the *one* prior. So a slight variation which incorporates the wording from @davecgh 's edit to the checklist in [PR 1451](https://github.com/decred/dcrd/pull/1451/files#diff-84c699cc270b08041d0a9b77522f68b8) (also referenced in the OP of this Issue) on what you've written could be:

```For projects using Go, ensure you have either the latest Go release or the one prior installed, as well as a working $GOPATH. All Go code changes for Decred must be compliant with the latest version of Go and the one prior to it.```

**Comment by s-ben** [comment]
Yeah that wording could be misleading. Good catch. The latest wording looks good to me 👍

**Comment by jholdstock** [comment]
As stated by @jrick, the $GOPATH var isnt actually required anymore. That leaves us with the following:

> For projects using Go, ensure you have either the latest Go release or the one prior installed. All Go code changes for Decred must be compliant with the latest version of Go and the one prior to it.

**Comment by PrimeDominus** [comment]
@jholdstock Reads good to me :)
