### ISSUE TITLE
Out of date info on PoW Mining page

### ISSUE THREAD

**Issue by s-ben** [decred/dcrdocs#674]
On the [proof-of-work](https://docs.decred.org/mining/proof-of-work/) page, there are a couple out-of-date items that need updating:

In first para:
> Each time a block is created (by a miner), about 30 new Decred coins are made. 

According to the [inflation](https://docs.decred.org/advanced/inflation/) page, the block reward for this month is ~20.

In second para:
> To get started, you must have a computer with a video card. Most video cards can be used for mining (including the “mobile” types found in some laptops). In general, higher end video cards perform at higher hashrates and therefore receive higher rewards.

While DCR can still be mined with GPUs, ASICs generally make it unprofitable. I think we should update this wording to say that mining can be done on GPUs and ASICs, but that most mining is now done by ASICs. (Optional) add warning that GPU mining may no longer be profitable, depending on your situation.

**Comment by jholdstock** [comment]
These seem like good improvements to me. Perhaps instead of having a definite number like 30 or 20, we could link to either the inflation chart (https://docs.decred.org/advanced/inflation/) or to the stats page (https://stats.decred.org/). That will prevent this page from falling out of date again in the future.

Nobody can say for sure where the hash power securing the network is coming from, so I would avoid the phrase "most mining is done by ASICs", but it's definitely worth mentioning that ASICs are now available, and since their inception the PoW difficulty has become high enough to make GPU mining unprofitable.
