### ISSUE TITLE
Update the standard fee in the glossary

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrdocs#742]
On the page https://docs.decred.org/glossary/#transaction-fees we need to update the standard fee to 0.0001 DCR/kB.

Quote from the release notes:
>fee rate that will be accepted and relayed to the rest of the network has been reduced to 0.0001 DCR/kB
Source: https://github.com/decred/decred-binaries/blob/master/release-notes.md

**Comment by s-ben** [comment]
@noahpierau , nice catch. Have opened a PR (https://github.com/decred/dcrdocs/pull/743). Just realized though that this number is in other places in the docs as well. Do we need to update the number elsewhere? For instance on pages talking about the fee for buying tickets?

**Comment by jholdstock** [comment]
This was deliberately left on the previous value due to the second paragraph in the release note:

> Transactions should not attempt to use the reduced fee rate until the majority of the network has upgraded to this release as otherwise the transactions will likely have issues relaying through the network since old nodes that have not updated their policy will reject them due to not paying a high enough fee.
We didnt want to encourage users to use 0.0001 when the majority of the network would reject it.

It's hard to get reliable data about whether the majority of the network has upgraded, but if we look at what we do know...

https://dcrstats.com/map
124 of the 203 (~61%) visible nodes are running 1.3.0 or later.

https://stats.decred.org/
48 out of 74 (~65%)  visible nodes are running 1.3.0 or later.

So I think we are probably at a point where updating the value makes sense.

As for the other instances of "0.001" in the docs, most of these are references to ticket fees which are still 0.001. There is a single instance which is referring to tx fee in `dcrd-and-dcrwallet-cli-arguments.md` -  the value listed here is the default value for the CLI flag which is actually still correct. It will probably change in 1.4.0
