### ISSUE TITLE
Contributor Compensation: warn about risks

### ISSUE THREAD

**Issue by xaur** [decred/dcrdocs#783]
For people who need to liquidate DCR to live, exchange rate can slash their salary in half (or increase it by 2x) _before_ they get a chance to liquidate it. Explaining the risk group and invoicing timeline would clear things up and set proper expectations to new contractors from the start.

**Comment by s-ben** [comment]
This is definitely an important topic (in this group myself and have taken a beating the last two invoices). I was aware of these risks when I signed up (net 30 means exposure to 30 days of volatility), but am thinking more about the issue now, and wondering if other contributors are as savvy and need better expectation management. Perhaps update the [Contributor Compensation](https://docs.decred.org/contributing/contributor-compensation/) page on dcrdocs?

A couple questions though. Recently @behindtext [mentioned](https://matrix.to/#/!MgQoetFiyjrHAywokv:decred.org/$154696746710995GhYai:decred.org?via=decred.org&via=matrix.org&via=zettaport.com) that we've gone from paying invoices net ~30 to net ~15. Is that permanent, or a temporary measure? Part of managing expectations is not putting numbers in official docs that might change and become outdated. 

Also, perhaps this is a different issue, but have been wondering about ways to manage volatility risk myself (e.g. possibly shorting the amount of DCR I'm expecting to get when I send in the invoice). If I find the time, want to figure out a) what is possible and b) what is responsible re: the DCR spot price.

**Comment by xaur** [comment]
Not sure what you mean by "net ~30". The average payout delay was reduced, which also reduced exposure to volatility. The plan is to reduce it further as possible, and that requires more automation (contractor-mgmt system). The docs should be clear about not promising any numbers but give an estimate "2-4 weeks into next month" or something.

I was wondering about DCR spot price too but that opens a whole can of attack worms.

When dealing with Treasury that can only pay in DCR, some entity or entities must absorb the volatility risk. It is either

1. the Treasury itself, if it pays some "extra" to protect from volatility
2. corporate contractor that gets DCR and pays employees in USD or in DCR at spot price (so the employee has a chance to liquidate and get expected USD)
3. independent individual billing directly, who can afford a long run (in theory it should smoothen over a long run)

One of these or a combination. A more exotic option is a special "DCR buffer" entity between the Treasury and indepentent contractors, but that also adds complexity and trust issues.

Main idea of this issue is to document what we have now to set expectations for people that might only realize the mechanic fully only when it happens.

**Comment by s-ben** [comment]
Yeah, don't mean to pull us off topic here. Agree that we should as clear as possible without promising numbers (which may change over time). And btw, the new shorter billing period definitely helped me this month (sold basically at the exchange rate at invoice). Perhaps for now, this can just be a short paragraph added to the 'Contractor Compansation' (or whatever we call it) page we're creating in https://github.com/decred/dcrdocs/issues/784 

To continue tangent: I bring up the volatility issue just because, while I hope to start accumulating DCR, staking, and "dollar cost averaging out" into USD over time (potentially catching some big upside), I'm currently having to sell most of my DCR for USD, and seeing that this is going to be an issue for other contractors poor in capitol, time, or knowledge about markets/trading. I actually know a bit about all this stuff from my adventures in algo trading (have deployed bots running on Binance), and am interested in the problem generally. When I have the time, I'm going to explore creating a little "DCR buffer" entity for myself and sharing the results with the community, just to see if other people find it valuable. I do see how exposing contractors could be valuable "game theory", creating more "skin in the game". And I see how complicated and fraught addressing this issue is. But I think having tools to manage volatility during what could be a protracted bear market for all could be a valuable selling point to those with more time than capitol. My 2 atoms.

**Comment by jholdstock** [comment]
Personally I don't think user documentation is the place to be talking about exchange rates or volatility, and certainly not the place for financial advice. 

Extending [this section](https://docs.decred.org/contributing/contributor-compensation/#contractors) to mention how the hourly rate is calculate and when payout typically happens (2-4 weeks) seems reasonable. That will allow the reader to make their own judgement, based on their own circumstances.

**Comment by s-ben** [comment]
Close this Issue? It seems we have this covered OK now in the [Contributor Compensation page](https://docs.decred.org/contributing/contributor-compensation/).

**Comment by jholdstock** [comment]
Agreed.

**Comment by xaur** [comment]
Agreed, the updated page covers it quite well. Thanks everyone.
