### ISSUE TITLE
General Computer Security

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdocs#799]
Jake has produced a starter text which can be used as the basis for a new page on general computer security tips.

http://zer0byte.com/zeropastebin/?ab1a6d1f916cf34a#rLZHxP2pl5sH8RfLE9DrWPA083RHTmy5mq/0T0RKewI=

**Comment by xaur** [comment]
Related: #816

**Comment by xaur** [comment]
That zeropaste expires in 8 days.

**Comment by s-ben** [comment]
Put in (public) gist,
https://gist.github.com/s-ben/3278d658e8785460f68bf497e22d248e

Assume this is OK because it's general knowledge, but can make private or put elsewhere if there's an issue. 

This is pretty well written, and could just be dropped into a page as is. Perhaps a 'Security' page under /Advanced? Or perhaps under /Wallets? The other option would just be to publish this elsewhere (Medium, etc.), as it's generally applicable and valuable to the community. Could just be Tweeted out by us or something.

**Comment by xaur** [comment]
Please, if Medium then only after it is in some Git. Medium censored a few cc-related articles recently and must not be treated as a primary hosting for documents, merely a mirror (one of many).
